# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-18 09:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Content',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notes', tinymce.models.HTMLField()),
                ('document', models.FileField(upload_to='multimedia/')),
                ('chapter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Chapters')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Subject')),
                ('topics', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Topics')),
            ],
        ),
    ]
