# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-18 09:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='document',
            field=models.FileField(blank=True, null=True, upload_to='multimedia/'),
        ),
    ]
